
SELECT LTRIM('   OLÁ') AS RESULTAD_LTRIM;

SELECT RTRIM('OLÁ   ') AS RESULTADO_RTRIM;

SELECT TRIM('   OLÁ   ') AS RESULTADO_TRIM;

SELECT CONCAT('OLÁ', ' ', 'TUDO BEM', '?') AS RESULTADO_CONCAT;

SELECT UPPER('olá, tudo bem?') AS RESULTADO_UPPER;

SELECT LOWER('OLÁ, TUDO BEM?') AS RESULTADO_LOWER;

SELECT SUBSTRING('OLÁ, TUDO BEM?', 6, 4) AS RESULTADO_SUBSTRING;

SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO_CONCAT FROM tabela_de_clientes;

SELECT CONCAT(NOME, ', ', ENDERECO_1, ', ', BAIRRO,
', ', CIDADE, ', ', ESTADO) AS DADOS_CLIENTE FROM tabela_de_clientes;

SELECT NOME, CONCAT(ENDERECO_1, ', ', BAIRRO,
', ', CIDADE, ', ', ESTADO) AS DADOS_CLIENTE FROM tabela_de_clientes;

